config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  resources :submissions
  resources :ratings
  resources :assignments
  root to: 'page#home'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, :controllers => {
    registrations: 'registrations'
  }
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  
  belongs_to :user
  has_many :submissions, dependent: :destroy
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:show, :index]

  # GET /assignments or /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1 or /assignments/1.json
  def show
    @submissions = @assignment.submissions 
    idforref = params[:id]
    flash[:asig_ref] = idforref
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments or /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)
    @assignment.user_id= current_user.id
    respond_to do |format|
      if @assignment.save
        format.html { redirect_to assignment_url(@assignment), notice: "Assignment was successfully created." }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1 or /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to assignment_url(@assignment), notice: "Assignment was successfully updated." }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1 or /assignments/1.json
  def destroy
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url, notice: "Assignment was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  # Upload is used to handle requests for uploading files
  def upload
    uploaded_file = params[:picture]
    File.open(Rails.root.join('public', 'uploads', uploaded_file.original_filename), 'wb') do |file|
      file.write(uploaded_file.read)
    end
  end

  

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assignment_params
      params.require(:assignment).permit(:title, :body)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignment.html.erb
<div class="card card-body border-0">
  <p>
    <strong><%= assignment.title %></strong> by @<%= assignment.user.email.split('@')[0] %>
    
  </p>

  <p>
    <%= assignment.body %>
  </p>

  <%= link_to '', assignment, class:"stretched-link" %>
  <%if current_user.role == "teacher" && User.find(assignment.user_id).id == current_user.id%>
  <% link_to 'Edit', edit_assignment_path(assignment)%>
  <%end%>
  <% link_to 'Back', assignments_path%>
</div>

app/views/assignments/_form.html.erb
<%= form_with(model: assignment) do |form| %>
  <% if assignment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>
      <ul>
        <% assignment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block", class:"form-label" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body, style: "display: block", class:"form-label" %>
    <%= form.text_area :body, class:"form-control" %>
  </div>

  <div class="mb-3 mt-3">
    <%= form.file_field :picture, class: "form-control"%>
  </div>    

  <div class="mt-3">
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>


<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render "form", assignment: @assignment %>

<br>

<div class="btn-group">
  <button class="btn btn-outline-primary" type="button">
    <%= link_to "Show this assignment", @assignment %>
  </button>

  <button class="btn btn-outline-primary" type="button">
    <%= link_to "Back to assignments", assignments_path %>
  </button>
</div>

app/views/assignments/index.html.erb
<h1>Assignments</h1> 

<%if current_user.role == "teacher" %>
  <div>
    <button class="btn btn-outline-success" type="button">
      <%= link_to "New assignment", new_assignment_path %>
    </button>
  </div>
<% end%>

<div class="mt-3" id="assignments">
  <% @assignments.each do |assignment| %>
    <div class="">
      <%= render assignment %>
    </div>
    <br>
  <% end %>
</div>

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render "form", assignment: @assignment %>

<br>

<div>
  <button class="btn btn-outline-primary" type="button">
    <%= link_to "Back to assignments", assignments_path %>
  </button>
</div>

app/views/assignments/show.html.erb
<h3>
  Assignment <%= @assignment.id %>
</h3> 

<%= render @assignment %>

<div class="btn-group mt-3 mb-3" style="">
<%if current_user.role == "teacher" && User.find(@assignment.user_id).id == current_user.id%>
  <button class="btn btn-outline-primary" type="submit">
    <%= link_to "Edit this assignment", edit_assignment_path(@assignment), class:"stretched-link" %>
  </button>

  <!--<button class="btn btn-outline-primary" type="submit">
    <%= link_to "Rate this assignment", new_rating_path(@assignment), class:"stretched-link" %>
  </button> -->
<%end%>
  <button class="btn btn-outline-primary" type="submit">
    <%= link_to "Back to assignments", assignments_path, class:"stretched-link" %>
  </button>

  
 
<%if (current_user.role == "teacher" && User.find(@assignment.user_id).id == current_user.id) || current_user.role == "student"%>
  <button class="btn btn-outline-success" type="button">
    <%= link_to "Add Submission", new_submission_path %>
  </button>
<%end%>
  <!--<%= link_to "Rate this assignment", new_rating_path(@assignment) %> |
  <%= link_to "Show ratings", ratings_path(@assignment) %> -->
</div>
<%if current_user.role == "teacher" && User.find(@assignment.user_id).id == current_user.id%>
<%= button_to "Destroy this assigment", @assignment, method: :delete, class: "btn btn-outline-danger" %>
<%end%>

<br>
<h5>
  Submissions:
</h5> 
<div id="assignments">
  <% @submissions.each do |submission| %>
    <%= render submission %>
    <br>
  <% end %>
</div>