config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  resources :submissions
  resources :ratings
  resources :assignments
  root to: 'page#home'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, :controllers => {
    registrations: 'registrations'
  }
end

app/models/rating.rb
class Rating < ApplicationRecord
    
    belongs_to :submission
    belongs_to :user
    
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:show, :index]

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
    refidsub= flash[:submis_ref]
    flash[:refsub] = refidsub
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create

    submis_id = flash[:refsub]
    @submission = Submission.find(submis_id)
   
    @rating = @submission.ratings.build(score: params[:rating][:score], body: params[:rating][:body])
    @rating.user_id = current_user.id
    if @rating.save
      redirect_to submissions_path
    else
      redirect to root_url
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to rating_url(@rating), notice: "Rating was successfully updated." }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url, notice: "Rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:score, :body, :submission_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating) do |form| %>
<%if rating.present?%>
  <% if rating.errors.any?  %>
    <div style="color: red">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

  <div class="mb-3">
    <%= form.label :score, style: "display: block", class:"form-label" %>
    <%= form.number_field :score, class:"form-control", min:1, max:10 %>
  </div>

  <div class="mb-3">
    <%= form.label :body, style: "display: block", class:"form-label" %>
    <%= form.text_area :body, class:"form-control" %>
  </div>

  <div class="mt-3">
  
    <%= form.submit class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/ratings/_rating.html.erb
<div class="card card-body border-0">
  <div id="<%= dom_id rating %>">
    <p>
      Rated <strong><%= rating.score %></strong> by @<%= rating.user.email.split('@')[0] %>
    </p>

    <p>
      <%= rating.body %>
    </p>

  <%= link_to '', rating, class:"stretched-link" %>
<%if current_user.role == "teacher" || User.find(rating.user_id).id == current_user.id%>
  <% link_to 'Edit', edit_rating_path(rating)%>
<%end%>
  <% link_to 'Back', ratings_path%>
  </div>
</div>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render "form", rating: @rating %>

<br>

<div class="btn-group">
  <button class="btn btn-outline-primary" type="button">
    <%= link_to "Show this rating", @rating %>
  </button>

  <button class="btn btn-outline-primary" type="button">
    <%= link_to "Back to ratings", ratings_path %>
  </button>
</div>

app/views/ratings/index.html.erb
<h1>Ratings</h1>

<div class="mt-3" id="ratings">
  <% @ratings.each do |rating| %>
    <div class="">
      <%= render rating %>
    </div>
    <br>
  <% end %>
</div>

<!--<div>
  <button class="btn btn-outline-success" type="button">
    <%= link_to "New rating", new_rating_path %>
  </button> -->
</div>

app/views/ratings/new.html.erb
<h1>New rating for Submission <%= flash[:submis_ref]%></h1>

<%= render "form", rating: @rating %>
  <form action="/addEval" method="post">


<br>

<div>
  <button class="btn btn-outline-primary" type="button">
    <%= link_to "Back to ratings", ratings_path %>
  </button>
</div>

app/views/ratings/show.html.erb
<br>
<%= render @rating %>


<div class="btn-group mt-3" style="">
<%if current_user.role == "teacher" || User.find(@rating.user_id).id == current_user.id%>
  <button class="btn btn-outline-primary" type="submit">
    <%= link_to "Edit this rating", edit_rating_path(@rating), class:"stretched-link" %>
  </button>
<%end%>

  <button class="btn btn-outline-primary" type="submit">
    <%= link_to "Show Submission", "/submissions/"+@rating.submission_id.to_s %>
  </button>

  <!--<%= link_to "Edit this rating", edit_rating_path(@rating) %> |
  <%= link_to "Back to ratings", ratings_path %> -->
</div>
<%if current_user.role == "teacher" || User.find(@rating.user_id).id == current_user.id%>
<%= button_to "Destroy this rating", @rating, method: :delete, class: "btn btn-outline-danger mt-3 mb-3" %>
<%end%>