config/routes.rb
Rails.application.routes.draw do
  get 'search', to: "search#index"
  resources :submissions
  resources :ratings
  resources :assignments
  root to: 'page#home'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users, :controllers => {
    registrations: 'registrations'
  }
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :assignment
  has_many :ratings, dependent: :destroy
  # validates :assignment_id, presence: false
  # validates :name, presence: false
  belongs_to :user
  

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:show, :index]

  # GET /submissions or /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1 or /submissions/1.json
  def show
    @ratings = @submission.ratings 
    # flash[:assignment_id] = params[:id]
    idforrefsub = params[:id]
    flash[:submis_ref] = idforrefsub

    
  end

  # GET /submissions/new
  def new
    #@assignment = Assignment.find(params[:assignment_id])
    @submission = Submission.new
    #@submission.assignment_id = @assignment.id
    refid= flash[:asig_ref]
    flash[:ref] = refid
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions or /submissions.json
  def create
    assig_id = flash[:ref]
    @assignment = Assignment.find(assig_id)
   
    @submission = @assignment.submissions.build(name: params[:submission][:name], description: params[:submission][:description])
    @submission.user_id = current_user.id

    if @submission.save
      redirect_to assignments_path
    else 
      redirect_to root_url
    end
    # respond_to do |format|
    #   if @submission.save
    #     format.html { redirect_to submission_url(@submission), notice: "Submission was successfully created." }
    #     format.json { render :show, status: :created, location: @submission }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @submission.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:title, :description, :assignment_id, :user_id)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_with(model: submission) do |form| %>
  <% if submission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="mb-3">
    <%= form.label :name, style: "display: block", class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block", class:"form-label" %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div>
    <div class="mt-3">
      <%= form.submit class: "btn btn-outline-primary" %>
    </div>
  </div>
<% end %>

app/views/submissions/_submission.html.erb
<div id="<%= dom_id submission %>">
<div class="card card-body border-0">
  <p>
    <strong>
      <%= submission.name%> 
    </strong>
    posted by @<%= User.find(submission.user_id).email.split('@')[0]%>
  </p>
  
  <p>
    <%= submission.description%>
  </p>

  <%= link_to "", submission, class:"stretched-link" %>
  <%if current_user.role == "teacher" || User.find(submission.user_id).id == current_user.id%>
  <% link_to 'Edit', edit_submission_path(submission)%>
  <%end%>
  
</div>
</div>

app/views/submissions/edit.html.erb
<h1>Editing submission for Assignment<%= flash[:asig_ref]%></h1>

<%= render "form", submission: @submission %>

<br>

<div class="btn-group">
  <button class="btn btn-outline-primary" type="button">
    <%= link_to "Show this submission", @submission %>
  </button>

  <button class="btn btn-outline-primary" type="button">
    <%= link_to "Back to submissions", submissions_path %>
  </button>
</div>

app/views/submissions/index.html.erb
<h1>Submissions</h1>

<div class="mt-3" id="submissions">
  <% @submissions.each do |submission| %>
    <%= render submission %>
    <p>
    </p>
  <% end %>
</div>

<!--<div>
  <button class="btn btn-outline-success" type="button">
    <%= link_to "New submission", new_submission_path %>
  </button> -->
</div>

app/views/submissions/new.html.erb
<h1>New submission for Assignment <%= flash[:asig_ref]%></h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <button class="btn btn-outline-primary" type="button">
    <%= link_to "Back to submissions", submissions_path %>
  </button>
</div>

app/views/submissions/show.html.erb
<h3>
  Submission <%= @submission.id %>
</h3> 

<%= render @submission %>

<div class="btn-group mt-3" style="">
<%if current_user.role == "teacher" || (current_user.role == "student" && User.find(@submission.user_id).id == current_user.id) %>
  <button class="btn btn-outline-primary" type="submit">
    <%= link_to "Edit this submisson", edit_submission_path(@submission), class:"stretched-link" %>
  </button>
<%end%>

  <button class="btn btn-outline-primary" type="submit">
    <%= link_to "View Assignment", "/assignments/"+@submission.assignment_id.to_s %>
  </button>
<%if !(User.find(@submission.user_id).id == current_user.id) %>
  <button class="btn btn-outline-success" type="submit">
    <%= link_to "Rate this submission", new_rating_path(@submission), class:"stretched-link" %>
  </button>
<%end%>

  <!--<%= link_to "Edit this submission", edit_submission_path(@submission) %> |
  <%= link_to "Back to submissions", submissions_path %> -->
</div>
<%if current_user.role == "teacher" || User.find(@submission.user_id).id == current_user.id%>
<%= button_to "Destroy this submission", @submission, method: :delete, class: "btn btn-outline-danger mt-3" %>
<%end%>
<br> <br>
<h5>
  Ratings:
</h5> 

<div id="submissions">
  <% @ratings.each do |rating| %>
    <%= render rating %>
    <br>
  <% end %>
</div>